releases:
  - name: paperless-ngx
    namespace: "home-services"
    chart: ../../charts/paperless-ngx
    values:
      - ingress:
          main:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: traefik
            hosts:
              - host: miniryzen
                paths:
                  - path: /paperless
                    pathType: Prefix
      - persistence:
          export:
            enabled: false
          consume:
            enabled: false

