repositories:
  - name: gabe565
    url: https://charts.gabe565.com

releases:
  - name: paperless-ngx
    namespace: "home-services"
    chart: gabe565/paperless-ngx
    version: 0.9.2
    values:
      - ingress:
        main:
          enabled: true
          annotations:
              kubernetes.io/ingress.class: traefik
          hosts:
          - host: miniryzen   
            paths:
              - path: /paperless
          

