apiVersion: batch/v1
kind: CronJob
metadata:
  name: paperless-export-cron
spec:
  schedule: "* */12 * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: sa-paperless-export-cron
          containers:
          - name: paperless-export
            image: bitnami/kubectl:latest
            command: ["/bin/sh","-c"]
            args: ['kubectl exec $(kubectl get pods --namespace home-services | grep "paperless-ngx" | grep -v "redis" | awk {"print $1}") -n home-services -- bash -c "mkdir -p /usr/src/paperless/media tmp_export && chown -c paperless /usr/src/paperless/media tmp_export && document_exporter -c /usr/src/paperless/media/tmp_export && cp /usr/src/paperless/media/tmp_export/* /usr/src/paperless/export" && echo "\n Backup finished"']
          restartPolicy: OnFailure


          