kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: home-services
  name: paperless-export-role
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - pods/exec
  verbs:
  - 'get'
  - 'list'
  - 'create'